import { IconName } from "@fortawesome/fontawesome-svg-core";
import { faAmazon, faBattleNet, faDiscord, faDocker, faFacebook, faFacebookF, faFacebookMessenger, faFontAwesome, faGit, faGitAlt, faGithub, faGithubAlt, faGitlab, faGoogle, faGooglePlay, faInstagram, faLinkedinIn, faMeta, faMicrosoft, faNode, faNodeJs, faPlaystation, faReadme, faSass, faSnapchat, faSpotify, faStackOverflow, faSteam, faSteamSymbol, faTailwindCss, faTelegram, faThreads, faTwitch, faVisualStudio, faXbox, faXTwitter, faYarn, faYoutube } from "@fortawesome/free-brands-svg-icons";
import { faBook, faBookOpen, faBookOpenReader, faBookReader, faBug, faBugSlash, faCamera, faCat, faCircleUser, faClipboard, faCode, faCodeBranch, faCodeFork, faCodePullRequest, faComment, faCopy, faDesktop, faDesktopAlt, faEject, faEllipsis, faEnvelope, faExclamation, faExclamationCircle, faExclamationTriangle, faGear, faGears, faHeart, faHouse, faI, faImage, faImages, faInfo, faInfoCircle, faKey, faKeyboard, faLock, faLockOpen, faMessage, faMinus, faPlus, faQuestion, faQuestionCircle, faScroll, faShare, faStar, faToolbox, faTrophy, faU, faX } from "@fortawesome/free-solid-svg-icons";

export const faIconMap = {
  'amazon': faAmazon,
  'battle-net': faBattleNet,
  'book': faBook,
  'book-open': faBookOpen,
  'book-reader': faBookReader,
  'book-open-reader': faBookOpenReader,
  'bug': faBug,
  'bug-slash': faBugSlash,
  'camera': faCamera,
  'cat': faCat,
  'circle-user': faCircleUser,
  'clipboard': faClipboard,
  'code': faCode,
  'code-branch': faCodeBranch,
  'code-fork': faCodeFork,
  'code-pull-request': faCodePullRequest,
  'comment': faComment,
  'copy': faCopy,
  'desktop': faDesktop,
  'desktop-alt': faDesktopAlt,
  'discord': faDiscord,
  'docker': faDocker,
  'eject': faEject,
  'ellipsis': faEllipsis,
  'envelope': faEnvelope,
  'exclamation': faExclamation,
  'exclamation-circle': faExclamationCircle,
  'exclamation-triangle': faExclamationTriangle,
  'facebook': faFacebook,
  'facebook-f': faFacebookF,
  'facebook-messenger': faFacebookMessenger,
  'font-awesome': faFontAwesome,
  'gear': faGear,
  'gears': faGears,
  'git': faGit,
  'git-alt': faGitAlt,
  'github': faGithub,
  'github-alt': faGithubAlt,
  'gitlab': faGitlab,
  'google': faGoogle,
  'google-play': faGooglePlay,
  'heart': faHeart,
  'house': faHouse,
  'i': faI,
  'image': faImage,
  'images': faImages,
  'info': faInfo,
  'info-circle': faInfoCircle,
  'instagram': faInstagram,
  'key': faKey,
  'keyboard': faKeyboard,
  'linkedin': faLinkedinIn,
  'lock': faLock,
  'lock-open': faLockOpen,
  'message': faMessage,
  'meta': faMeta,
  'microsoft': faMicrosoft,
  'minus': faMinus,
  'node': faNode,
  'node-js': faNodeJs,
  'playstation': faPlaystation,
  'plus': faPlus,
  'question': faQuestion,
  'question-circle': faQuestionCircle,
  'readme': faReadme,
  'sass': faSass,
  'scroll': faScroll,
  // 'scss': faSass,
  'share': faShare,
  'snapchat': faSnapchat,
  'spotify': faSpotify,
  'stack-overflow': faStackOverflow,
  'star': faStar,
  'steam': faSteam,
  'steam-symbol': faSteamSymbol,
  'tailwind-css': faTailwindCss,
  'telegram': faTelegram,
  'threads': faThreads,
  'toolbox': faToolbox,
  'trophy': faTrophy,
  'twitch': faTwitch,
  'u': faU,
  'visual-studio': faVisualStudio,
  'x': faX,
  'x-twitter': faXTwitter,
  'xbox': faXbox,
  'yarn': faYarn,
  'youtube': faYoutube,
};

/**
 * A **FontAwesome** icon.
 * @see {@link IconName}
 * @see {@link IconDefinition}
 * @see {@link faIconMap}
 */
export type FaIconKind = keyof typeof faIconMap;

export const faIconKinds: IconName[] = Object.keys(faIconMap).map(k => k as IconName);
